#!/bin/bash

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Make sure a domain is passed in
if [[ $# -eq 0 ]] ; then
    echo 'use: mksite domain.com'
    exit 0
fi

DOMAIN=$1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Make sure site doesn't already exist
does_file_exist () {
  if ! [ -f $1 ]; then
     ALL_IS_HERE=false
  fi
} 
does_dir_exist () {
  if ! [ -d $1 ]; then
     ALL_IS_HERE=false
  fi
} 

ALL_IS_HERE=true

does_file_exist "/etc/nginx/sites-available/$DOMAIN"
does_file_exist "/etc/nginx/sites-enabled/$DOMAIN"
does_dir_exist  "/srv/www/$DOMAIN/"

if $ALL_IS_HERE ; then
  echo "Sorry, $DOMAIN already exists."
  exit 1
else
  echo "Creating $DOMAIN..."
fi

### BASICS ###

# Install nginx sites-available.

cp "$DIR/default" "/etc/nginx/sites-available/$DOMAIN"
sed -i "s/domain/$DOMAIN/g" "/etc/nginx/sites-available/$DOMAIN"

ln -s "/etc/nginx/sites-available/$DOMAIN" "/etc/nginx/sites-enabled/$DOMAIN"

mkdir --parents "/srv/www/$DOMAIN/"

service nginx reload

# Download WordPress
wget http://wordpress.org/latest.zip -P "/srv/www/$DOMAIN/"
unzip "/srv/www/$DOMAIN/latest.zip" -d "/srv/www/$DOMAIN/"
rm -rf "/srv/www/$DOMAIN/latest.zip"
mv "/srv/www/$DOMAIN/wordpress/" "/srv/www/$DOMAIN/public_html/"

# Ask for username, passsword, change domain to dbname
read -p "Username: " USERNAME
read -p "Password: " PASSWORD
DB_NAME=${DOMAIN/\./_}

echo $USERNAME $PASSWORD $DB_NAME

# Create database
mysql -uroot -p -e "create database $DB_NAME; grant all privileges on $DB_NAME.* to $USERNAME@localhost identified by '$PASSWORD'; flush privileges;"


# Confirm files were made
ALL_IS_HERE=true

does_file_exist "/etc/nginx/sites-available/$DOMAIN"
does_file_exist "/etc/nginx/sites-enabled/$DOMAIN"
does_dir_exist  "/srv/www/$DOMAIN/public_html"

if $ALL_IS_HERE ; then
  echo "Created $DOMAIN!"
else
  echo "Sorry, something went wrong."
fi

